### ISSUE TITLE
Use external DirSuite tool (DirSuite Mk3)?

### ISSUE THREAD

**Issue by jaa127** [hrj/abandon#125]
Hello,

This issue is about using external DirSuite depency for Abandon.

I have released DirSuite Mk3 as an open source project. It contains similar features as with Abandon, and new, previously internal features. 

Most notably it can run multiple execution steps per one test.  It also supports for running test cases without any arguments or configuration. This is needed, if and when Abandon supports autodiscovery of configuration. (There is code in utils-fs to find out run path, and that can be used to find default configuration).

There is also an option to run test in multistep failure mode, where first execution steps must succeed and then the last must fail (e.g. "init", "do something", "do failure").

DirSuite is hosted on github, it's under Apache 2 license, and Artifacts are published on Maven Central Repository.

Test syntax is pretty similar to what is in use with Abandon at the moment, and there is easy extension point for Abandon specific use cases ("-X", "-q" and "-c" "conf-file" automatic args). I can provide patch to change test cases to new `exec-file` format.

It would also be only test depency, so it won't affect runtime configurations (if utils-fs is not integrated).  Based on experience with Abandon and from internal use, I would say the external interfaces are pretty stable at the moment.

It also has very extensive test framework and test coverage, and it specifically tests and validates some corner cases (e.g. wrong pattern, which doesn't fine any tests, wrong dirsuite path, etc.)
 * https://travis-ci.org/sn127/utils/builds/193829748
 * https://coveralls.io/builds/9771808

It also has good? documentation, so it would be possible to point new people to that, if they hack Abandon (instead to internally explaining how DirSuite works).

What do you think, would it make sense to use DirSuite Mk3 with Abandon?

Below are few links:
 * Project: https://github.com/sn127/utils
 * User Guide: https://github.com/sn127/utils/blob/master/docs/dirsuite.md
 * Abandon specifc example:  https://github.com/sn127/utils/blob/master/examples/src/test/scala/MapArgsDemo.scala
 * Runnable example project: https://github.com/sn127/utils/tree/master/examples

Let me know what do you think, and I can prepare PR if you like to move in this direction.

Best Regards,
Jani

**Comment by hrj** [comment]
@jaa127 Sounds great, and you have already addressed all the questions I might have thought of. :smile: 

Please go ahead with the PR!

**Comment by jaa127** [comment]
Ok, Great to hear that! There is now PR #127.

**Comment by hrj** [comment]
Closed via PR #127
