### ISSUE TITLE
Cannot parse a simple file

### ISSUE THREAD

**Issue by przemekd** [hrj/abandon#290]
I wasn't able to parse a really simple transaction log:

```
2019-02-01 Opening Balance
  Assets:BNP Paribas checking account  1000.00
  Equity:Opening Balances
```
and the error output is pretty much useless:
```
[1.1] failure: end of input expected

2019-02-01 Opening Balance
^
Input error: Couldn't parse input
```

**Comment by hrj** [comment]
abandon doesn't allow spaces in the account name. This is to keep the code simple and prevent weird corner cases while parsing.

For visual separation between words, I recommend using `_` (underscore) or CamelCase.

best,
HRJ
