### ISSUE TITLE
Api access?

### ISSUE THREAD

**Issue by drozzy** [hrj/abandon#66]
Hi, guys.
How should I use abandon from my won scala code? Any recommendations?

I see that it reads data from a file - is there a way to feed it just a string?
Similarly for commands, can they be issued at the scala level? I.e. register, balance etc...

**Comment by hrj** [comment]
@drozzy To be frank, we haven't designed an API as such for abandon. However, what you ask should be possible; we feed strings in the test suite. See [this file](https://github.com/hrj/abandon/blob/master/base/src/test/scala/co/uproot/abandon/ProcessorTest.scala) for example.

Let me know if you hit any problems, or have ideas for making a proper API.

**Comment by drozzy** [comment]
Thanks, I saw that. Are there any examples of how to call "balance" or "register" for example? I'm not sure I understand where that is actually invoked.

**Comment by hrj** [comment]
@drozzy check the latest master branch: I have simplified the tests a bit and also did some minor refactoring. The functions to create balance, register and other reports are actually invoked in the `cli` and `gui` modules.

To give a little background, this project is structured as follows:

The `base` module provides the main functionality. The `cli` and `gui` are frontends to this functionality. So you can think of `base` as providing an API, and the `cli` and `gui` consume this API and pretty print the results.

There are three main functionalities that the `base` module provides:
* Parsing (convert string into an AST)
* Processing (accept AST as input and then balance the accounts)
* Reporting (take the output of Processing and create reports)

Some of this is documented in [this wiki page](https://github.com/hrj/abandon/wiki/Developer:Overview). I am also adding the above information to it now.

**Comment by drozzy** [comment]
Thanks. So what would you say is a process flow if I want to use abandon in the backend, I am thinking something like this (correct me where I'm wrong):

1. Given a list of transactions and a command like "balance"
2. Convert them to a string (ledger format)
3. Use abandon to parse it into AST
4. Process AST
5. Run `balance` report on output of above (somehow? not sure about this part yet)

P.S.: I don't really care for efficiency here, just trying to avoid re-writing ledger. So converting my internal data to strings is just fine with me.

**Comment by hrj** [comment]
Yeah, your process flow is fine. Here's a complete example:

```scala
    val testInput = """
    2016/1/2
      Expense                -200
      Cash
    """
    val parseResult = AbandonParser.abandon(scanner(testInput))
    parseResult match {
      case AbandonParser.Success(astEntries, _) =>
        val appState = Processor.process(astEntries, Nil)

        val balSettings = BalanceReportSettings("title", None, Nil, true)
        val settings = Settings(Nil, Nil, Nil, Seq(balSettings), ReportOptions(Nil), Nil, None)
        val balanceReport = Reports.balanceReport(appState, settings, balSettings)
        println(balanceReport)

    }
```

**Comment by drozzy** [comment]
I'm happy to report it works beautifully :-)
Here is how I format the report:

`balanceReport._1.map(_.render).mkString("\n")`

Small typo: it should be `ParserHelper.scanner` not just `scanner`.
