### ISSUE TITLE
Sbt Maven central?

### ISSUE THREAD

**Issue by drozzy** [hrj/abandon#68]
Have you thought about putting the project on maven, so that one could simply reference it in sbt dependencies?

**Comment by drozzy** [comment]
It seems doing `sbt publish-local` only publishes the main `src` directory, and doesn't actually include all the subprojects.
Any idea how to include them?

**Comment by hrj** [comment]
I have never published before. I have just now registered on Sonatype and requested for publishing there.

I plan to publish three different artifacts; one each for `base`, `cli` and `gui`. I don't know what changes would be required in sbt configuration to achieve that. I need to explore.

> It seems doing sbt publish-local only publishes the main src directory, and doesn't actually include all the subprojects. Any idea how to include them?

Can you try publishing them individually? That is, `sbt base/publish-local` etc.

**Comment by drozzy** [comment]
I just dropped the jar in my lib dependencies for now.

I'll wait till it's up on maven before referencing them from sbt :-)
Thanks.

**Comment by hrj** [comment]
I still haven't got a response from Sonatype. I will keep this issue open till it's published.

**Comment by hrj** [comment]
I got a positive response from sonatype. I will publish as soon as I find some time.

**Comment by hrj** [comment]
It's done! I have released version 0.3.0 RC1.

Organisation: `in.co.uproot`
Artifact Id: `abandon-base_2.11` (2.11 is the scala version)
Version: `0.3.0-rc1`

Other artifacts are `abandon_cli_2.11`, `abandon_gui_2.11`, and the whole package `abandon_2.11`.

@drozzy I haven't actually tried using it. If you do, please give me your feedback.
