### ISSUE TITLE
Allow multiple comment entries in single line notation

### ISSUE THREAD

**Issue by hrj** [hrj/abandon#97]
#### Syntax

```
. <date> <account-name> <amount>     ; comment 1 ; comment 2 ; comment 3
```

**Comment by hrj** [comment]
I imagine the extra comments would become transaction level comments. By "extra" I mean: One of the comments (first or last) can remain a post comment. The remaining can become transaction comments.

**Comment by hrj** [comment]
If we follow this syntax for all comments, not just single line notation, then existing input files will be processed differently. Comments with a `;` in them will treated as two comments, instead of one.

@gerdreiss @jaa127 @alexanderzafirov @Entea  Thoughts?

**Comment by jaa127** [comment]
Maybe it would be better to keep all multiple comments targeting closing object, e.g. journal / scope, transaction or posting.  This would make it possible to overload comments to convey e.g. metadata

For example:

````
; journal / scope level comment
2017-02-26 describtion
      ;:uuid: 135612f9-6ae1-4d60-94a5-263e454932f5
      ; txn comment
      expenses:e   1;:tag:t1,t2,t3,t4;:x-meta-info: some metadata; Actual post comment
      assets:a 
````
Then we will have:

 - journal with one comment
 - Txn with
    - 1 metadata (`uuid`)
    - 1 comment
 - posting with
   - tag-cloud (`t1`,`t2`,`t3`, `t4`)
   - metadata (`x-meta-info`)
   - actual comment

With ANTLR-based parser, I have used notation that comment is `;<space>` so `;` alone could be used for non-comment content space (for example `;:`)

**Comment by hrj** [comment]
@jaa127 Good ideas there. Need to think about tags in detail.

As far as this particular issue, I think we will keep it simple. Extra comments in single-line-notation will become txn level comments.

**Comment by hrj** [comment]
> If we follow this syntax for all comments, not just single line notation, then existing input files will be processed differently.

Oh and for now, we will make the syntax change only for single-line-notation. Otherwise it will affect older input files.

**Comment by jaa127** [comment]
I think there is bigger semantic problem than just tags or support for metadata. 
If user put a comment at the end of posting, then it was ment to be for that posting. If it was supposed to be for transaction level comment, then it could have easily been written as such.

Now if above is true or agreed, then it is highly suprising to find some of your  posting comments as transaction comments on output (e.g. ledger export)  as they are changing location between input and output journal.

**Comment by hrj** [comment]
> If user put a comment at the end of posting, then it was ment to be for that posting. If it was supposed to be for transaction level comment, then it could have easily been written as such.

The main thrust of this issue is "single line notation" where it not possible to enter transaction level comment normally. Single line notation looks something like this:

```
. date  account   amount   ; optional comment
```

This is a short-hand for:
```
date
  account   amount    ; optional comment
  defaultAccount
```

We could allow an additional comment at the beginning of the short form which would become a transaction comment. However the entries won't be neatly aligned.

So I thought extra comments at the end of the line can become transaction level comments.

**Comment by jaa127** [comment]
Oh, I see, It seems that the main problem problem here is that two different DSL are stepping on each others toes. =/

**Comment by hrj** [comment]
@jaa127  Yeah, sort of :)

I am trying to wring maximum mileage out of the short hand notation without complicating it too much. The new commenting rule doesn't seem very complicated, so adding it in. But I will try not to add other such rules in the future. We should just expect the user to use the long-form whenever the need arises.

**Comment by jaa127** [comment]
Actually it should be possible to recognize these two cases:

In compact form you have `date  account   amount ; comments` when with full transaction syntact that line is starting with `space+ account amount; comments*` 

Maybe it's not worth of it, dunno.

**Comment by hrj** [comment]
Closed via https://github.com/hrj/abandon/pull/143

Thanks @gerdreiss
